name: certificate-clustering
services:
- name: certificate-segregator
  source_dir: /
  github:
    repo: CognicAI/Certificate-Clustering
    branch: main
    deploy_on_push: true
  run_command: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8080"
  - key: STREAMLIT_SERVER_PORT
    value: "8080"
  - key: STREAMLIT_SERVER_ADDRESS
    value: "0.0.0.0"
  - key: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - key: key
    scope: RUN_TIME
    type: SECRET
