[global]
developmentMode = false

[server]
headless = false
enableCORS = false
enableXsrfProtection = false
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
